services:
    firefox:
        image: eecs388/firefox
        restart: always
        # Allocate sufficient memory to the Firefox GUI process.
        # If your machine is running out of memory, you might try decreasing this,
        # though Firefox may run into instability if you do so.
        shm_size: 2g
        # Access browser via http://localhost:5800 in your browser,
        # or by vnc://localhost:5800 in a VNC client.
        ports:
            - 3880:5800
            - 3881:5900
        volumes:
            - ..:/workspaces/lab2
            - ./prefs.js:/config/.ffprofile/prefs.js
            - ./mozilla.cfg:/opt/firefox/mozilla.cfg
    stealer:
        build: .
        volumes:
            - ..:/workspaces/lab2
        # Prevent container from instantly exiting, allowing us to attach terminal
        command: /bin/sh -c "sleep infinity"
